// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketSystem.Api.Data;

#nullable disable

namespace TicketSystem.Api.Migrations
{
    [DbContext(typeof(TicketDbContext))]
    [Migration("20220228092829_AddLine")]
    partial class AddLine
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TicketSystem.Api.Entities.Booker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BookerPwd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("BookerWx")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasMaxLength(10)
                        .HasColumnType("tinyint(10)");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNum")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("TimeOfRegister")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Bookers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99e5b121-ef55-4e35-8d72-89d5622b73d1"),
                            BookerPwd = "123456",
                            BookerWx = "1",
                            DateOfBirth = new DateTime(2000, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "李",
                            Gender = 1,
                            IsDeleted = false,
                            LastName = "黑沙",
                            PhoneNum = "12345678901",
                            TimeOfRegister = new DateTime(2022, 2, 28, 17, 28, 29, 439, DateTimeKind.Local).AddTicks(868),
                            UserName = "黑沙"
                        });
                });

            modelBuilder.Entity("TicketSystem.Api.Entities.Line", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("EndTerminal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("StartTerminal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("StopStation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Lines");

                    b.HasData(
                        new
                        {
                            Id = new Guid("92d0ada0-2cd0-4cc9-b03d-3eccf17ab1a5"),
                            EndTerminal = "哈尔滨站",
                            StartTerminal = "广州站",
                            StopStation = "广州站,武汉站,北京站,哈尔滨站"
                        },
                        new
                        {
                            Id = new Guid("18c9ecbb-dc2c-43e8-ba77-9a6cef3ac9bc"),
                            EndTerminal = "成都站",
                            StartTerminal = "广州站",
                            StopStation = "广州站,重庆站,成都站"
                        },
                        new
                        {
                            Id = new Guid("cbead21b-0681-4a1a-853f-d5b61fd48f54"),
                            EndTerminal = "上海站",
                            StartTerminal = "广州站",
                            StopStation = "广州站,武汉站,上海站"
                        },
                        new
                        {
                            Id = new Guid("10687777-24de-4a07-a677-633031ae1009"),
                            EndTerminal = "哈尔滨站",
                            StartTerminal = "上海站",
                            StopStation = "上海站,北京站,哈尔滨站"
                        },
                        new
                        {
                            Id = new Guid("e7ff44ba-c4f9-40c8-a5a0-9ddc557f6093"),
                            EndTerminal = "成都站",
                            StartTerminal = "上海站",
                            StopStation = "上海站,武汉站,重庆站,成都站"
                        },
                        new
                        {
                            Id = new Guid("ee3e7e33-2c85-46c9-98e5-b4bf10f32576"),
                            EndTerminal = "广州站",
                            StartTerminal = "上海站",
                            StopStation = "上海站,武汉站,广州站"
                        },
                        new
                        {
                            Id = new Guid("b2187869-2f9f-4ea0-99b4-b8e5c8f34f3d"),
                            EndTerminal = "广州站",
                            StartTerminal = "哈尔滨站",
                            StopStation = "哈尔滨站,北京站,武汉站,广州站"
                        },
                        new
                        {
                            Id = new Guid("ee9e796d-fbfe-42c2-8eb4-b9674206ebc7"),
                            EndTerminal = "上海站",
                            StartTerminal = "哈尔滨站",
                            StopStation = "哈尔滨站,北京站,上海站"
                        },
                        new
                        {
                            Id = new Guid("fec134b0-8623-42db-8602-b64cce2912c2"),
                            EndTerminal = "成都站",
                            StartTerminal = "哈尔滨站",
                            StopStation = "哈尔滨站,北京站,武汉站,重庆站,成都站"
                        },
                        new
                        {
                            Id = new Guid("804edb5e-2bce-43e7-b34b-6db68a9ceb27"),
                            EndTerminal = "广州站",
                            StartTerminal = "成都站",
                            StopStation = "成都站,重庆站,广州站"
                        },
                        new
                        {
                            Id = new Guid("ba2b1c71-bff6-4507-ad15-99c6e13bb5fa"),
                            EndTerminal = "上海站",
                            StartTerminal = "成都站",
                            StopStation = "成都站,重庆站,武汉站,上海站"
                        },
                        new
                        {
                            Id = new Guid("c9c55cc8-2185-40b8-b85b-55c34c918f66"),
                            EndTerminal = "哈尔滨站",
                            StartTerminal = "成都站",
                            StopStation = "成都站,重庆站,武汉站,北京站,哈尔滨"
                        });
                });

            modelBuilder.Entity("TicketSystem.Api.Entities.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsTerminal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4b501cb3-d168-4cc0-b375-48fb33f318a4"),
                            IsTerminal = true,
                            StationName = "广州站"
                        },
                        new
                        {
                            Id = new Guid("7eaa532c-1be5-472c-a738-94fd26e5fad6"),
                            IsTerminal = false,
                            StationName = "重庆站"
                        },
                        new
                        {
                            Id = new Guid("72457e73-ea34-4e02-b575-8d384e82a481"),
                            IsTerminal = false,
                            StationName = "北京站"
                        },
                        new
                        {
                            Id = new Guid("b091b148-8fc7-4ce5-a6c5-c61dbbb3f91f"),
                            IsTerminal = true,
                            StationName = "上海站"
                        },
                        new
                        {
                            Id = new Guid("0846ff99-37ac-4849-804b-1eefac46d651"),
                            IsTerminal = true,
                            StationName = "成都站"
                        },
                        new
                        {
                            Id = new Guid("07c4638c-48b7-4783-88a5-58f47e2a0458"),
                            IsTerminal = true,
                            StationName = "哈尔滨站"
                        },
                        new
                        {
                            Id = new Guid("09626794-5565-452e-85a4-b924805588ba"),
                            IsTerminal = false,
                            StationName = "武汉站"
                        });
                });

            modelBuilder.Entity("TicketSystem.Api.Entities.Train", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("TrainName")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("TypeOfTrain")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Trains");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cc2a984d-cd07-4329-9b22-84a5c0185ea7"),
                            TrainName = "K48",
                            TypeOfTrain = "K"
                        },
                        new
                        {
                            Id = new Guid("e185afad-aa89-4d4e-bba0-391ce821ae9d"),
                            TrainName = "K11",
                            TypeOfTrain = "K"
                        },
                        new
                        {
                            Id = new Guid("99e5b121-ef55-4e35-8d72-89d5622b73db"),
                            TrainName = "D1868",
                            TypeOfTrain = "D"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
