// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketSystem.Api.Data;

#nullable disable

namespace TicketSystem.Api.Migrations
{
    [DbContext(typeof(TicketDbContext))]
    [Migration("20220321215242_update_redis")]
    partial class update_redis
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TicketSystem.Api.Entities.Booker", b =>
                {
                    b.Property<int>("BookerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BookerPwd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasMaxLength(10)
                        .HasColumnType("tinyint(10)");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNum")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("TimeOfRegister")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("BookerId");

                    b.ToTable("Bookers");

                    b.HasData(
                        new
                        {
                            BookerId = 1,
                            BookerPwd = "123456",
                            CardId = "453009200001013710",
                            DateOfBirth = new DateTime(2000, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "李",
                            Gender = 1,
                            IsDeleted = false,
                            LastName = "黑沙",
                            PhoneNum = "13600291522",
                            TimeOfRegister = new DateTime(2022, 3, 22, 5, 52, 42, 198, DateTimeKind.Local).AddTicks(2232),
                            UserName = "黑沙"
                        });
                });

            modelBuilder.Entity("TicketSystem.Api.Entities.Line", b =>
                {
                    b.Property<int>("LineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("EndTerminal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("StartTerminal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("StopStation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("TrainName")
                        .HasColumnType("longtext");

                    b.HasKey("LineId");

                    b.ToTable("Lines");

                    b.HasData(
                        new
                        {
                            LineId = 1,
                            EndTerminal = "哈尔滨站",
                            StartTerminal = "广州站",
                            StopStation = "广州站,武汉站,北京站,哈尔滨站"
                        },
                        new
                        {
                            LineId = 2,
                            EndTerminal = "成都站",
                            StartTerminal = "广州站",
                            StopStation = "广州站,重庆站,成都站"
                        },
                        new
                        {
                            LineId = 3,
                            EndTerminal = "上海站",
                            StartTerminal = "广州站",
                            StopStation = "广州站,武汉站,上海站"
                        },
                        new
                        {
                            LineId = 4,
                            EndTerminal = "哈尔滨站",
                            StartTerminal = "上海站",
                            StopStation = "上海站,北京站,哈尔滨站"
                        },
                        new
                        {
                            LineId = 5,
                            EndTerminal = "成都站",
                            StartTerminal = "上海站",
                            StopStation = "上海站,武汉站,重庆站,成都站"
                        },
                        new
                        {
                            LineId = 6,
                            EndTerminal = "广州站",
                            StartTerminal = "上海站",
                            StopStation = "上海站,武汉站,广州站"
                        },
                        new
                        {
                            LineId = 7,
                            EndTerminal = "广州站",
                            StartTerminal = "哈尔滨站",
                            StopStation = "哈尔滨站,北京站,武汉站,广州站"
                        },
                        new
                        {
                            LineId = 8,
                            EndTerminal = "上海站",
                            StartTerminal = "哈尔滨站",
                            StopStation = "哈尔滨站,北京站,上海站"
                        },
                        new
                        {
                            LineId = 9,
                            EndTerminal = "成都站",
                            StartTerminal = "哈尔滨站",
                            StopStation = "哈尔滨站,北京站,武汉站,重庆站,成都站"
                        },
                        new
                        {
                            LineId = 10,
                            EndTerminal = "广州站",
                            StartTerminal = "成都站",
                            StopStation = "成都站,重庆站,广州站"
                        },
                        new
                        {
                            LineId = 11,
                            EndTerminal = "上海站",
                            StartTerminal = "成都站",
                            StopStation = "成都站,重庆站,武汉站,上海站"
                        },
                        new
                        {
                            LineId = 12,
                            EndTerminal = "哈尔滨站",
                            StartTerminal = "成都站",
                            StopStation = "成都站,重庆站,武汉站,北京站,哈尔滨站"
                        });
                });

            modelBuilder.Entity("TicketSystem.Api.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("BookerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EndTerminal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EndTerminalId")
                        .HasColumnType("int");

                    b.Property<string>("StartTerminal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StartTerminalId")
                        .HasColumnType("int");

                    b.Property<int>("TrainId")
                        .HasColumnType("int");

                    b.Property<string>("TrainName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("price")
                        .HasColumnType("double");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TicketSystem.Api.Entities.Station", b =>
                {
                    b.Property<int>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsTerminal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("StationId");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            StationId = 1,
                            IsTerminal = true,
                            StationName = "广州站"
                        },
                        new
                        {
                            StationId = 2,
                            IsTerminal = false,
                            StationName = "重庆站"
                        },
                        new
                        {
                            StationId = 3,
                            IsTerminal = false,
                            StationName = "北京站"
                        },
                        new
                        {
                            StationId = 4,
                            IsTerminal = true,
                            StationName = "上海站"
                        },
                        new
                        {
                            StationId = 5,
                            IsTerminal = true,
                            StationName = "成都站"
                        },
                        new
                        {
                            StationId = 6,
                            IsTerminal = true,
                            StationName = "哈尔滨站"
                        },
                        new
                        {
                            StationId = 7,
                            IsTerminal = false,
                            StationName = "武汉站"
                        });
                });

            modelBuilder.Entity("TicketSystem.Api.Entities.Train", b =>
                {
                    b.Property<int>("TrainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time(6)");

                    b.Property<string>("TrainName")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("TypeOfTrain")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("TrainId");

                    b.HasIndex("LineId");

                    b.HasIndex("TrainName")
                        .IsUnique();

                    b.ToTable("Trains");

                    b.HasData(
                        new
                        {
                            TrainId = 1,
                            LineId = 1,
                            Time = new TimeOnly(14, 30, 0),
                            TrainName = "Z112",
                            TypeOfTrain = "Z"
                        },
                        new
                        {
                            TrainId = 2,
                            LineId = 2,
                            Time = new TimeOnly(12, 30, 0),
                            TrainName = "D1849",
                            TypeOfTrain = "D"
                        },
                        new
                        {
                            TrainId = 3,
                            LineId = 3,
                            Time = new TimeOnly(8, 50, 0),
                            TrainName = "K528",
                            TypeOfTrain = "K"
                        },
                        new
                        {
                            TrainId = 4,
                            LineId = 4,
                            Time = new TimeOnly(19, 12, 0),
                            TrainName = "G1204",
                            TypeOfTrain = "G"
                        },
                        new
                        {
                            TrainId = 5,
                            LineId = 5,
                            Time = new TimeOnly(11, 45, 0),
                            TrainName = "D636",
                            TypeOfTrain = "D"
                        },
                        new
                        {
                            TrainId = 6,
                            LineId = 6,
                            Time = new TimeOnly(7, 10, 0),
                            TrainName = "K527",
                            TypeOfTrain = "K"
                        },
                        new
                        {
                            TrainId = 7,
                            LineId = 7,
                            Time = new TimeOnly(15, 55, 0),
                            TrainName = "K728",
                            TypeOfTrain = "K"
                        },
                        new
                        {
                            TrainId = 8,
                            LineId = 8,
                            Time = new TimeOnly(14, 3, 0),
                            TrainName = "G1202",
                            TypeOfTrain = "G"
                        },
                        new
                        {
                            TrainId = 9,
                            LineId = 9,
                            Time = new TimeOnly(8, 20, 0),
                            TrainName = "K518",
                            TypeOfTrain = "K"
                        },
                        new
                        {
                            TrainId = 10,
                            LineId = 10,
                            Time = new TimeOnly(10, 10, 0),
                            TrainName = "K488",
                            TypeOfTrain = "K"
                        },
                        new
                        {
                            TrainId = 11,
                            LineId = 11,
                            Time = new TimeOnly(17, 0, 0),
                            TrainName = "G2195",
                            TypeOfTrain = "G"
                        },
                        new
                        {
                            TrainId = 12,
                            LineId = 12,
                            Time = new TimeOnly(18, 40, 0),
                            TrainName = "K546",
                            TypeOfTrain = "K"
                        });
                });

            modelBuilder.Entity("TicketSystem.Api.Entities.Train", b =>
                {
                    b.HasOne("TicketSystem.Api.Entities.Line", "Line")
                        .WithMany("Trains")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("TicketSystem.Api.Entities.Line", b =>
                {
                    b.Navigation("Trains");
                });
#pragma warning restore 612, 618
        }
    }
}
